### ISSUE TITLE
Potential circular import problem

### ISSUE THREAD

**Issue by Dvermetten** [jeroenrook/robustranking#1]
When trying to execute any robustranking code outside of the main 'robustranking' folder, it fails on import. 

Error message:
>>> import robustranking
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/diedie/venvs/venv_Algorithms/lib/python3.10/site-packages/robustranking/__init__.py", line 1, in <module>
    from . import utils
ImportError: cannot import name 'utils' from partially initialized module 'robustranking' (most likely due to a circular import) (/home/diedie/venvs/venv_Algorithms/lib/python3.10/site-packages/robustranking/__init__.py)

When running the same with the active directory being 'robustranking', it works as expected. Python 3.10.12, most recent version of the robustranking package.

**Comment by jeroenrook** [comment]
Imports are now absolute, type_checking imports are now not imported at runtime and importing tests are written.
